# Generated by Django 6.0.4 on 2026-04-10 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('sala', 'Sala'), ('lab', 'Laboratório')], max_length=10)),
                ('capacidade', models.PositiveIntegerField()),
                ('possui_computadores', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tipo'], name='reservas_es_tipo_22caa0_idx'), models.Index(fields=['capacidade'], name='reservas_es_capacid_226181_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.espaco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', 'hora_inicio'],
                'indexes': [models.Index(fields=['data'], name='reservas_re_data_e9422b_idx'), models.Index(fields=['espaco'], name='reservas_re_espaco__cf4091_idx'), models.Index(fields=['usuario'], name='reservas_re_usuario_cdc4d6_idx')],
            },
        ),
    ]
