# Generated by Django 6.0.4 on 2026-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
    ]
